"""fila de trabalho

Revision ID: ad82017ad2cf
Revises: 0003_rls_role
Create Date: 2026-09-21 14:47:42.638400
"""

from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "0004_jobs"
down_revision = "0003_rls_role"
branch_labels = None
depends_on = None


PREDICADO = "(tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid)"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "run_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dedupe_key", sa.String(length=200), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_jobs_claim", "jobs", ["status", "run_at"], unique=False)
    op.create_index(op.f("ix_jobs_dedupe_key"), "jobs", ["dedupe_key"], unique=False)
    op.create_index("ix_jobs_tenant_created", "jobs", ["tenant_id", "created_at"], unique=False)
    op.create_index(op.f("ix_jobs_tenant_id"), "jobs", ["tenant_id"], unique=False)
    # ### end Alembic commands ###
    _aplicar_rls()


def _aplicar_rls() -> None:
    """Tabela com dado de cliente nasce isolada, sem exceção.

    Esquecer isso numa tabela nova é o jeito mais fácil de reabrir o furo que
    a migration 0003 fechou — por isso a política vem junto da criação, e o
    teste que confere a lista cobre esta tabela também.
    """
    op.execute("ALTER TABLE jobs ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE jobs FORCE ROW LEVEL SECURITY")
    op.execute(f"CREATE POLICY tenant_isolation ON jobs USING {PREDICADO} WITH CHECK {PREDICADO}")
    # O acesso do role de aplicação vem de `scripts/bootstrap_roles.py`, que
    # concede em todas as tabelas e deixa ALTER DEFAULT PRIVILEGES para as
    # próximas. Conceder aqui, e ainda por cima a PUBLIC, daria acesso a
    # qualquer role do banco.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_jobs_tenant_id"), table_name="jobs")
    op.drop_index("ix_jobs_tenant_created", table_name="jobs")
    op.drop_index(op.f("ix_jobs_dedupe_key"), table_name="jobs")
    op.drop_index("ix_jobs_claim", table_name="jobs")
    op.drop_table("jobs")
    # ### end Alembic commands ###
